INSERT INTO `ipe`.`bairros`
(`id`,`nome`,`id_ser`)
VALUES
(null,'Vila Velha',1),
(null,'Jardim Guanabara',1),
(null,'Jardim Iracema',1),
(null,'Barra do Ceará',1),
(null,'Floresta',1),
(null,'Álvaro Weyne',1),
(null,'Cristo Redentor',1),
(null,'Ellery',1),
(null,'São Gerardo',1),
(null,'Monte Castelo',1),
(null,'Carlito Pamplona',1),
(null,'Pirambu',1),
(null,'Farias Brito',1),
(null,'Jacarecanga',1),
(null,'Moura Brasil',1),
(null,'Aldeota',2),
(null,'Cais do Porto',2),
(null,'Cidade 2000',2),
(null,'Cocó',2),
(null,'De Lourdes',2),
(null,'Dionísio Torres',2),
(null,'Engenheiro Luciano Calvalcante',2),
(null,'Guararapes',2),
(null,'Joaquim Távora',2),
(null,'Manuel Dias Branco',2),
(null,'Meireles',2),
(null,'Mucuripe',2),
(null,'Papicu',2),
(null,'Praia de Iracema',2),
(null,'Praia do Futuro I',2),
(null,'Praia do Futuro II',2),
(null,'Salinas',2),
(null,'São João do Tauape',2),
(null,'Varjota',2),
(null,'Vicente Pinzon',2),
(null,'Amadeu Furtado',3),
(null,'Antônio Bezerra',3),
(null,'Autran Nunes',3),
(null,'Bonsucesso',3),
(null,'Bela Vista',3),
(null,'Dom Lustosa',3),
(null,'Henrique Jorge',3),
(null,'João XXIII',3),
(null,'Jóquei Clube',3),
(null,'Olavo Oliveira',3),
(null,'Padre Andrade',3),
(null,'Parque Araxá',3),
(null,'Pici',3),
(null,'Parquelândia',3),
(null,'Presidente Kennedy',3),
(null,'Rodolfo Teófilo',3),
(null,'Quintino Cunha',3),
(null,'São José Bonifácio',4),
(null,'Benfica',4),
(null,'Fátima',4),
(null,'Jardim América',4),
(null,'Damas',4),
(null,'Parreão',4),
(null,'Bom Futuro',4),
(null,'Vila União',4),
(null,'Montese',4),
(null,'Couto Fernandes',4),
(null,'Pan Americano',4),
(null,'Demócrito Rocha',4),
(null,'Itaoca',4),
(null,'Parangaba',4),
(null,'Serrinha',4),
(null,'Aeroporto',4),
(null,'Itaperi',4),
(null,'Dendê',4),
(null,'Vila Pery',4),
(null,'Conjunto Ceará',5),
(null,'Siqueira',5),
(null,'Mondubim',5),
(null,'Conjunto José Walter',5),
(null,'Granja Lisboa',5),
(null,'Granja Portugal',5),
(null,'Bom Jardim',5),
(null,'Genibaú',5),
(null,'Canindezinho',5),
(null,'Vila Manoel Sátiro',5),
(null,'Parque São José',5),
(null,'Parque Santa Rosa',5),
(null,'Maraponga',5),
(null,'Jardim Cearense',5),
(null,'Conjunto Esperança',5),
(null,'Presidente Vargas',5),
(null,'Planalto Ayrton Senna',5),
(null,'Novo Mondubim',5),
(null,'Aerolândia',6),
(null,'Ancuri',6),
(null,'Alto da Balança',6),
(null,'Barroso',6),
(null,'Boa Vista',6),
(null,'Cambeba',6),
(null,'Cajazeiras',6),
(null,'Cidade dos Funcionários',6),
(null,'Coaçu',6),
(null,'Conjunto Palmeiras',6),
(null,'Curió',6),
(null,'Dias Macedo',6),
(null,'Edson Queiroz',6),
(null,'Guajerú',6),
(null,'Jangurussu',6),
(null,'Jardim das Oliveiras',6),
(null,'José de Alencar',6),
(null,'Messejana',6),
(null,'Parque Dois Irmãos',6),
(null,'Passaré',6),
(null,'Paupina',6),
(null,'Parque Manibura',6),
(null,'Parque Iracema',6),
(null,'Parque Santa Maria',6),
(null,'Pedras',6),
(null,'Lagoa Redonda',6),
(null,'Sabiaguaba',6),
(null,'São Bento',6),
(null,'Sapiranga',6),
(null,'Centro',7);



